.TH "includes Directory Reference" 3 "Thu Mar 9 2023" "Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtlcllists\&.h\fP"
.br
.ti -1c
.RI "file \fBtlcmaths\&.h\fP"
.br
.ti -1c
.RI "file \fBtlcstdios\&.h\fP"
.br
.ti -1c
.RI "file \fBtlcstdlibs\&.h\fP"
.br
.ti -1c
.RI "file \fBtlcstrings\&.h\fP"
.br
.ti -1c
.RI "file \fBtlcutils\&.h\fP"
.br
.in -1c
