.TH "any_t::value_s" 3Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
any_t::value_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlcjson\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBstr\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "float \fBf\fP"
.br
.ti -1c
.RI "list_t * \fBarray\fP"
.br
.ti -1c
.RI "dico_t * \fBdict\fP"
.br
.ti -1c
.RI "char \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBtlcjson\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "list_t* any_t::value_s::array"

.PP
Definition at line \fB36\fP of file \fBtlcjson\&.h\fP\&.
.SS "char any_t::value_s::c"

.PP
Definition at line \fB38\fP of file \fBtlcjson\&.h\fP\&.
.SS "dico_t* any_t::value_s::dict"

.PP
Definition at line \fB37\fP of file \fBtlcjson\&.h\fP\&.
.SS "float any_t::value_s::f"

.PP
Definition at line \fB35\fP of file \fBtlcjson\&.h\fP\&.
.SS "int any_t::value_s::i"

.PP
Definition at line \fB34\fP of file \fBtlcjson\&.h\fP\&.
.SS "char* any_t::value_s::str"

.PP
Definition at line \fB33\fP of file \fBtlcjson\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for (my)TinyLibC from the source code\&.
