.TH "any_t" 3Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
any_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlcjson\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBvalue_s\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBany_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "union \fBany_s::value_s\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBtlcjson\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBany_type_t\fP any_t::type"

.PP
Definition at line \fB31\fP of file \fBtlcjson\&.h\fP\&.
.SS "union \fBany_s::value_s\fP any_t::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for (my)TinyLibC from the source code\&.
