.TH "circ_buf_inf_t" 3Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
circ_buf_inf_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlccirc_buf_inf\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "list_t * \fBbuffer\fP"
.br
.ti -1c
.RI "const char * \fBend_pattern\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBtlccirc_buf_inf\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "list_t* circ_buf_inf_t::buffer"

.PP
Definition at line \fB16\fP of file \fBtlccirc_buf_inf\&.h\fP\&.
.SS "const char* circ_buf_inf_t::end_pattern"

.PP
Definition at line \fB17\fP of file \fBtlccirc_buf_inf\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for (my)TinyLibC from the source code\&.
