.TH "dico_node_t" 3Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dico_node_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlcdico\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBkey\fP [256]"
.br
.ti -1c
.RI "void * \fBvalue\fP"
.br
.ti -1c
.RI "void(* \fBdestroy\fP )(void *\fBvalue\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBtlcdico\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "void(* dico_node_t::destroy) (void *\fBvalue\fP)"

.PP
Definition at line \fB21\fP of file \fBtlcdico\&.h\fP\&.
.SS "char dico_node_t::key[256]"

.PP
Definition at line \fB19\fP of file \fBtlcdico\&.h\fP\&.
.SS "void* dico_node_t::value"

.PP
Definition at line \fB20\fP of file \fBtlcdico\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for (my)TinyLibC from the source code\&.
