.TH "json_t" 3Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlcjson\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "any_t * \fBdico\fP"
.br
.ti -1c
.RI "int \fBnb_keys\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB43\fP of file \fBtlcjson\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "any_t* json_t::dico"

.PP
Definition at line \fB44\fP of file \fBtlcjson\&.h\fP\&.
.SS "int json_t::nb_keys"

.PP
Definition at line \fB45\fP of file \fBtlcjson\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for (my)TinyLibC from the source code\&.
