.TH "list_t" 3 "Thu Mar 9 2023" "Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlcllists\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "node_t * \fBstart\fP"
.br
.ti -1c
.RI "node_t * \fBend\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBtlcllists\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "node_t* list_t::end"

.PP
Definition at line \fB25\fP of file \fBtlcllists\&.h\fP\&.
.SS "int list_t::len"

.PP
Definition at line \fB26\fP of file \fBtlcllists\&.h\fP\&.
.SS "node_t* list_t::start"

.PP
Definition at line \fB24\fP of file \fBtlcllists\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for (my)TinyLibC from the source code\&.
