.TH "node_result_t" 3 "Thu Mar 9 2023" "Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_result_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlcllists\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "node_t * \fBnode_ptr\fP"
.br
.ti -1c
.RI "int \fBnode_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBtlcllists\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int node_result_t::node_index"

.PP
Definition at line \fB32\fP of file \fBtlcllists\&.h\fP\&.
.SS "node_t* node_result_t::node_ptr"

.PP
Definition at line \fB31\fP of file \fBtlcllists\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for (my)TinyLibC from the source code\&.
