.TH "llnodesearch" 3 "Fri Jul 22 2022" "Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llnodesearch
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlcllists\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnode_t\fP * \fBnode_ptr\fP"
.br
.ti -1c
.RI "int \fBnode_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBtlcllists\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int llnodesearch::node_index"

.PP
Definition at line \fB32\fP of file \fBtlcllists\&.h\fP\&.
.SS "\fBnode_t\fP* llnodesearch::node_ptr"

.PP
Definition at line \fB31\fP of file \fBtlcllists\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for (my)TinyLibC from the source code\&.
