.TH "includes/tlcutils.h" 3 "Fri Jul 22 2022" "Version 0.0.1" "(my)TinyLibC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/tlcutils.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfree_ifnotnull\fP (void *ptr)"
.br
.RI "free if \fCptr\fP is not null "
.ti -1c
.RI "void \fBreturn_void\fP (void)"
.br
.RI "function that do nothing; utils for ternary with one function call "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void free_ifnotnull (void * ptr)"

.PP
free if \fCptr\fP is not null 
.PP
\fBParameters\fP
.RS 4
\fIptr\fP to free 
.RE
.PP

.SS "void return_void (void)"

.PP
function that do nothing; utils for ternary with one function call 
.SH "Author"
.PP 
Generated automatically by Doxygen for (my)TinyLibC from the source code\&.
